import type { Metadata } from "next";
import { Raleway } from "next/font/google";

import "./globals.css";
import { Footer, NavbarTop } from "@/components/ui";
import SmoothScrolling from "@/components/ui/SmoothScrolling";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const raleway = Raleway({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${raleway.className} antialiased`}>
        <SmoothScrolling>
          <NavbarTop />

          {children}
          <Footer />
        </SmoothScrolling>
      </body>
    </html>
  );
}
